SET FOREIGN_KEY_CHECKS=0;

TRUNCATE TABLE `Prevenir`;
TRUNCATE TABLE `Pers_Coord`;
TRUNCATE TABLE `Personne`;
TRUNCATE TABLE `Ecole`;
TRUNCATE TABLE `Coordonnees`;
TRUNCATE TABLE `Classe`;
TRUNCATE TABLE `Pers_Classe`;


SET FOREIGN_KEY_CHECKS=1;